### ISSUE TITLE
Disabled mods not displaying correctly

### ISSUE THREAD

**Issue by Jian-Ng** [Wolfmyths/Myth-Mod-Manager#28]
Disabled mods show up as disabled initially, but displayed as enabled on refresh. The feature itself is working correctly.
Thank you for the speedy fix on issue #25.

https://github.com/Wolfmyths/Myth-Mod-Manager/assets/110548158/c66b91cf-d2e6-4b84-a713-d2707852e31b

**Comment by Wolfmyths** [comment]
I'll check it out, since it works at a functional standpoint it'll either be patched if another big bug is found. Or until the next feature update (mod profiles)

**Comment by Wolfmyths** [comment]
I'm not sure what caused this, but it has been fixed in the latest feature update *(Which should be out pretty soon)* 🤷

Thanks for the report I'll add it to the known bugs list on the changelog.

**Comment by Wolfmyths** [comment]
It turns out the issue was because when the mod list refreshes, it looks for the disabled mods directory which didn't have a fallback value on specifically one line of code.

This means if you did not change the disabled mods folder directory option, this bug will happen since there's no value set there in your options.

> I'm not sure what caused this, but it has been fixed in the latest feature update

Yeah I was wrong about this haha, well its fixed for sure now 😄
