### ISSUE TITLE
Suggestion: Skip mod button when enable/disabling mods

### ISSUE THREAD

**Issue by 0jrv** [Wolfmyths/Myth-Mod-Manager#31]
add a skip button to the enable/disable mods
some mods take a while to disable so it would be good if you could skip it

**Comment by Wolfmyths** [comment]
I'll see if it's possible to do something like that

When you cancel enabling/disabling mods, it actually doesn't revert any of the changes made up until where you stopped because you'd need to move those mods back, which would take even longer

I also tell the program to finish the current step when canceling for a couple reasons:

1. To prevent any risk of file corruption (I have to do more research on the module I'm using to manage files to make sure it's safe)

2. The files are iterated through a for loop, so iterations cannot be skipped outside the for loops scope (theres a couple of workarounds for this)

Thanks for the suggestion! I'll definitely think about it

**Comment by Wolfmyths** [comment]
Unfortunately I believe this is impossible I've tried a lot of approaches over the months.

In mock testing it worked but when dealing with real files it would result in crashing without any error message.
