### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by VJohnston13** [Wolfmyths/Myth-Mod-Manager#58]
I got an update notice, but it hits 99% and just stays on writing for the rest of time... and since I can't minimize it, the window is in the way of everything else on my screen...

**Comment by Wolfmyths** [comment]
Did any errors come up in the logs folder?
Also what version are you on?

You can also update manually by downloading the latest update from the releases page and replacing your current exe

**Comment by VJohnston13** [comment]
That was a fast answer!

I am on version 1.3.0. I am also noticing that I am unable to start payday 2 from the manager.

I tried to update yesterday when I remembered I have the app, upon opening the mod manager, but it stayed stuck at 99% just saying Writing... I fear I may have to update manually. It won't lose the mods this way, right?

**Comment by VJohnston13** [comment]
I skipped over your asking about the logs folder. I am not sure where that is or what file(s) you are asking about.

**Comment by Wolfmyths** [comment]
> I am not sure where that is or what file(s) you are asking about.

Theres a logs folder where you installed the mod manager, open it with a text editor and scroll down to see the latest logs. Whenever certain things happen in the program (Like an error) it will write there.

> I am on version 1.3.0. I am also noticing that I am unable to start payday 2 from the manager.

Not being able to start payday 2 from myth mod manager should be already fixed in the latest update.
The current issue you are having might already be fixed too.

> It won't lose the mods this way, right?

Nope! If you're replacing the executable nothing should change.
Mods are stored where they usually are as if you weren't using the program.
Disabled mods are moved into a folder that is in the same directory as myth mod manager by default, which can be changed in the settings.
Be careful because changing a disabled mod's folder will not move the currently disabled mods to the new location. (I should probably add that as an update)

**Comment by Wolfmyths** [comment]
I'm gonna close this issue.
I just downloaded the latest update (1.6.0 -> 1.6.1) and I had no issue personally.

Your issue must be from an earlier bug and there haven't been any other reports about this.
